-d E:\sonhaftadersi\fpga_odev2\impl\gwsynthesis\fpga_odev2.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\sonhaftadersi\fpga_odev2\src\fpga_odev2.cst
-cfg E:\sonhaftadersi\fpga_odev2\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
